export declare const MIN_WIDTH = 320;
export declare const MAX_WIDTH = 1728;
export declare const MAX_WIDTH_CONTAINER = 1420;
export declare const SECOND_MAX_CONTAINER = 1720;
export declare const CONTAINER_PADDING = 30;
export declare const CONTAINER_WIDTH: number;
export declare const PC: number;
export declare const TABLET = 991.98;
export declare const MOBILE = 767.98;
export declare const MOBILE_SMALL = 479.98;
export declare const MAIN_SIZE = 16;
export declare const TITLE_SIZE = 18;
export declare const FONT_SIZE_LOGO = 75;
export declare const FONT_WEIGHT_LOGO = 400;
export declare const BACKGROUND_COLOR_MAIN = "#f3efef";
export declare const BACKGROUND_COLOR_SECOND = "#ffffff";
export declare const FONT_SIZE_TITLE = 26;
export declare const FONT_WEIGHT_MAIN_TEXT = 400;
export declare const LINE_HEIGHT_MAIN_TEXT = 1.25;
