export declare const BtnAddTask: import("styled-components/dist/types").IStyledComponentBase<"web", import("styled-components").FastOmit<import("@mui/lab/LoadingButton").LoadingButtonOwnProps & Omit<import("@mui/material").ButtonOwnProps & Omit<import("@mui/material").ButtonBaseOwnProps, "classes">, "classes"> & Omit<import("@mui/material").ButtonBaseOwnProps, "classes"> & import("@mui/material/OverridableComponent").CommonProps & Omit<Omit<import("react").DetailedHTMLProps<import("react").ButtonHTMLAttributes<HTMLButtonElement>, HTMLButtonElement>, "ref"> & {
    ref?: ((instance: HTMLButtonElement | null) => void | import("react").DO_NOT_USE_OR_YOU_WILL_BE_FIRED_CALLBACK_REF_RETURN_VALUES[keyof import("react").DO_NOT_USE_OR_YOU_WILL_BE_FIRED_CALLBACK_REF_RETURN_VALUES]) | import("react").RefObject<HTMLButtonElement> | null | undefined;
}, "className" | "style" | "tabIndex" | "color" | "children" | "size" | "disabled" | "href" | "action" | "loading" | "variant" | "classes" | "fullWidth" | "sx" | "centerRipple" | "disableRipple" | "disableTouchRipple" | "focusRipple" | "focusVisibleClassName" | "LinkComponent" | "onFocusVisible" | "TouchRippleProps" | "touchRippleRef" | "disableElevation" | "startIcon" | "endIcon" | "loadingIndicator" | "disableFocusRipple" | "loadingPosition">, never>> & string & Omit<import("@mui/material").ExtendButton<import("@mui/lab/LoadingButton").LoadingButtonTypeMap<{}, "button">>, keyof import("react").Component<any, {}, any>>;
export declare const BtnDeleteTask: import("styled-components/dist/types").IStyledComponentBase<"web", import("styled-components").FastOmit<import("@mui/lab/LoadingButton").LoadingButtonOwnProps & Omit<import("@mui/material").ButtonOwnProps & Omit<import("@mui/material").ButtonBaseOwnProps, "classes">, "classes"> & Omit<import("@mui/material").ButtonBaseOwnProps, "classes"> & import("@mui/material/OverridableComponent").CommonProps & Omit<Omit<import("react").DetailedHTMLProps<import("react").ButtonHTMLAttributes<HTMLButtonElement>, HTMLButtonElement>, "ref"> & {
    ref?: ((instance: HTMLButtonElement | null) => void | import("react").DO_NOT_USE_OR_YOU_WILL_BE_FIRED_CALLBACK_REF_RETURN_VALUES[keyof import("react").DO_NOT_USE_OR_YOU_WILL_BE_FIRED_CALLBACK_REF_RETURN_VALUES]) | import("react").RefObject<HTMLButtonElement> | null | undefined;
}, "className" | "style" | "tabIndex" | "color" | "children" | "size" | "disabled" | "href" | "action" | "loading" | "variant" | "classes" | "fullWidth" | "sx" | "centerRipple" | "disableRipple" | "disableTouchRipple" | "focusRipple" | "focusVisibleClassName" | "LinkComponent" | "onFocusVisible" | "TouchRippleProps" | "touchRippleRef" | "disableElevation" | "startIcon" | "endIcon" | "loadingIndicator" | "disableFocusRipple" | "loadingPosition">, never>> & string & Omit<import("@mui/material").ExtendButton<import("@mui/lab/LoadingButton").LoadingButtonTypeMap<{}, "button">>, keyof import("react").Component<any, {}, any>>;
export declare const BtnDeleteTasks: import("styled-components/dist/types").IStyledComponentBase<"web", import("styled-components").FastOmit<import("@mui/lab/LoadingButton").LoadingButtonOwnProps & Omit<import("@mui/material").ButtonOwnProps & Omit<import("@mui/material").ButtonBaseOwnProps, "classes">, "classes"> & Omit<import("@mui/material").ButtonBaseOwnProps, "classes"> & import("@mui/material/OverridableComponent").CommonProps & Omit<Omit<import("react").DetailedHTMLProps<import("react").ButtonHTMLAttributes<HTMLButtonElement>, HTMLButtonElement>, "ref"> & {
    ref?: ((instance: HTMLButtonElement | null) => void | import("react").DO_NOT_USE_OR_YOU_WILL_BE_FIRED_CALLBACK_REF_RETURN_VALUES[keyof import("react").DO_NOT_USE_OR_YOU_WILL_BE_FIRED_CALLBACK_REF_RETURN_VALUES]) | import("react").RefObject<HTMLButtonElement> | null | undefined;
}, "className" | "style" | "tabIndex" | "color" | "children" | "size" | "disabled" | "href" | "action" | "loading" | "variant" | "classes" | "fullWidth" | "sx" | "centerRipple" | "disableRipple" | "disableTouchRipple" | "focusRipple" | "focusVisibleClassName" | "LinkComponent" | "onFocusVisible" | "TouchRippleProps" | "touchRippleRef" | "disableElevation" | "startIcon" | "endIcon" | "loadingIndicator" | "disableFocusRipple" | "loadingPosition">, never>> & string & Omit<import("@mui/material").ExtendButton<import("@mui/lab/LoadingButton").LoadingButtonTypeMap<{}, "button">>, keyof import("react").Component<any, {}, any>>;
export declare const BtnAddTasks: import("styled-components/dist/types").IStyledComponentBase<"web", import("styled-components").FastOmit<import("@mui/lab/LoadingButton").LoadingButtonOwnProps & Omit<import("@mui/material").ButtonOwnProps & Omit<import("@mui/material").ButtonBaseOwnProps, "classes">, "classes"> & Omit<import("@mui/material").ButtonBaseOwnProps, "classes"> & import("@mui/material/OverridableComponent").CommonProps & Omit<Omit<import("react").DetailedHTMLProps<import("react").ButtonHTMLAttributes<HTMLButtonElement>, HTMLButtonElement>, "ref"> & {
    ref?: ((instance: HTMLButtonElement | null) => void | import("react").DO_NOT_USE_OR_YOU_WILL_BE_FIRED_CALLBACK_REF_RETURN_VALUES[keyof import("react").DO_NOT_USE_OR_YOU_WILL_BE_FIRED_CALLBACK_REF_RETURN_VALUES]) | import("react").RefObject<HTMLButtonElement> | null | undefined;
}, "className" | "style" | "tabIndex" | "color" | "children" | "size" | "disabled" | "href" | "action" | "loading" | "variant" | "classes" | "fullWidth" | "sx" | "centerRipple" | "disableRipple" | "disableTouchRipple" | "focusRipple" | "focusVisibleClassName" | "LinkComponent" | "onFocusVisible" | "TouchRippleProps" | "touchRippleRef" | "disableElevation" | "startIcon" | "endIcon" | "loadingIndicator" | "disableFocusRipple" | "loadingPosition">, never>> & string & Omit<import("@mui/material").ExtendButton<import("@mui/lab/LoadingButton").LoadingButtonTypeMap<{}, "button">>, keyof import("react").Component<any, {}, any>>;
